[project]
name = "newsletter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mysql-connector-python>=9.0.0",
]

[dependency-groups]
dev = [
    "neovim>=0.3.1",
]
